# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eeff9574ad1d6b5b065bba6d41452f7418055f0c7a0d539c91c23b567c696e66e67dd86be3d9b321b6372b0e79c0681b780ea189d6d27919e0aab351d440adbf

test:
  secret_key_base: 2ad165173b6de3f1fa16e37dee431180135ff5ee5aee7f196e5a4fde16216663c6225811c4badd5811b33c1fe31ecf19252d462b2edd651faa1a9f6fc38bfc8d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
