User.create!([
  {name: "jumanji"},
  {name: "fezzik"},
  {name: "humperdink"},
  {name: "flash"}
])
Work.create!([
  {category: "album", title: "Can't Buy a Thrill", creator: "Steely Dan", description: nil, publication_year: 1972, vote_count: 0},
  {category: "album", title: "Countdown to Ecstasy", creator: "Steely Dan", description: nil, publication_year: 1973, vote_count: 0},
  {category: "album", title: "Pretzel Logic", creator: "Steely Dan", description: nil, publication_year: 1974, vote_count: 0},
  {category: "album", title: "Katy Lied", creator: "Steely Dan", description: nil, publication_year: 1975, vote_count: 0},
  {category: "album", title: "The Royal Scam", creator: "Steely Dan", description: nil, publication_year: 1976, vote_count: 0},
  {category: "album", title: "Aja", creator: "Steely Dan", description: nil, publication_year: 1977, vote_count: 0},
  {category: "album", title: "Gaucho", creator: "Steely Dan", description: nil, publication_year: 1980, vote_count: 0},
  {category: "album", title: "Silence Yourself", creator: "Savages", description: nil, publication_year: 2013, vote_count: 0},
  {category: "album", title: "Adore Life", creator: "Savages", description: nil, publication_year: 2016, vote_count: 0},
  {category: "album", title: "NVM", creator: "Tacocat", description: nil, publication_year: 2014, vote_count: 0},
  {category: "album", title: "Lost Time", creator: "Tacocat", description: nil, publication_year: 2016, vote_count: 0},
  {category: "album", title: "No Regrets", creator: "Chastity Belt", description: nil, publication_year: 2013, vote_count: 0},
  {category: "album", title: "Time to Go Home", creator: "Chastity Belt", description: nil, publication_year: 2015, vote_count: 0},
  {category: "album", title: "Sleater-Kinney", creator: "Sleater-Kinney", description: nil, publication_year: 1995, vote_count: 0},
  {category: "album", title: "Call the Doctor", creator: "Sleater-Kinney", description: nil, publication_year: 1996, vote_count: 0},
  {category: "album", title: "Dig Me Out", creator: "Sleater-Kinney", description: nil, publication_year: 1997, vote_count: 0},
  {category: "album", title: "The Hot Rock", creator: "Sleater-Kinney", description: nil, publication_year: 1999, vote_count: 0},
  {category: "album", title: "All Hands on the Bad One", creator: "Sleater-Kinney", description: nil, publication_year: 2000, vote_count: 0},
  {category: "album", title: "No Cities to Love", creator: "Sleater-Kinney", description: nil, publication_year: 2015, vote_count: 0},
  {category: "book", title: "A Wizard of Earthsea", creator: "Ursula K. Leguin", description: nil, publication_year: 1968, vote_count: 0},
  {category: "movie", title: "Inside Out", creator: "Pixar", description: "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.", publication_year: 2015, vote_count: 0},
  {category: "movie", title: "Labyrinth", creator: "Jim Henson", description: "A 16-year-old girl is given 13 hours to solve a labyrinth and rescue her baby brother when her wish for him to be taken away is granted by the Goblin King.", publication_year: 1986, vote_count: 1},
  {category: "book", title: "Hidden Figures", creator: "Margot Lee Shetterly", description: "Good book that came before the movie", publication_year: 2016, vote_count: 1},
  {category: "book", title: "Kindred", creator: "Octavia E. Butler", description: "Good sci-fi book", publication_year: 1979, vote_count: 1},
  {category: "album", title: "The Woods", creator: "Sleater-Kinney", description: nil, publication_year: 2005, vote_count: 1},
  {category: "movie", title: "The Princess Bride", creator: "Rob Reiner", description: "While home sick in bed, a young boy's grandfather reads him a story called The Princess Bride.", publication_year: 1987, vote_count: 1},
  {category: "movie", title: "Zootopia", creator: "Disney", description: "In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy.", publication_year: 2016, vote_count: 1},
  {category: "book", title: "Practical Object-Oriented Design in Ruby", creator: "Sandi Metz", description: "Good programming book", publication_year: 2012, vote_count: 1},
  {category: "book", title: "Parable of the Sower", creator: "Octavia E. Butler", description: nil, publication_year: 1993, vote_count: 1}
])
